import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import { Jost } from 'next/font/google'
import Footer from "@/components/Footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-jost',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.variable}>
        <main className="flex-[1,1,auto] max-w-screen-xl mx-auto px-5 sm:px-10 lg:px-20">
        <Header/>
          {children}
          <Footer />
        </main>
        </body>
    </html>
  );
}
